/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OptionsForm.java
 *
 * Created on Nov 17, 2012, 7:56:38 AM
 */
package knottheorist;

/**
 *
 * @author erhannis
 */
public class OptionsForm extends javax.swing.JFrame {
    public KnotTheoristView parent;
    
    /** Creates new form OptionsForm */
    public OptionsForm(KnotTheoristView parent) {
        this.parent = parent;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupGridTheme = new javax.swing.ButtonGroup();
        radioGridNormal = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        radioGridInvisible = new javax.swing.JRadioButton();
        radioGridBW = new javax.swing.JRadioButton();
        radioGridMinimal = new javax.swing.JRadioButton();

        setName("Form"); // NOI18N

        groupGridTheme.add(radioGridNormal);
        radioGridNormal.setSelected(true);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("knottheorist/resources/OptionsForm"); // NOI18N
        radioGridNormal.setText(bundle.getString("radioGridNormal.text")); // NOI18N
        radioGridNormal.setName("radioGridNormal"); // NOI18N
        radioGridNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioGridNormalActionPerformed(evt);
            }
        });

        jLabel1.setText(bundle.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        groupGridTheme.add(radioGridInvisible);
        radioGridInvisible.setText(bundle.getString("radioGridInvisible.text")); // NOI18N
        radioGridInvisible.setName("radioGridInvisible"); // NOI18N
        radioGridInvisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioGridInvisibleActionPerformed(evt);
            }
        });

        groupGridTheme.add(radioGridBW);
        radioGridBW.setText(bundle.getString("radioGridBW.text")); // NOI18N
        radioGridBW.setName("radioGridBW"); // NOI18N
        radioGridBW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioGridBWActionPerformed(evt);
            }
        });

        groupGridTheme.add(radioGridMinimal);
        radioGridMinimal.setText(bundle.getString("radioGridMinimal.text")); // NOI18N
        radioGridMinimal.setName("radioGridMinimal"); // NOI18N
        radioGridMinimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioGridMinimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioGridNormal)
                            .addComponent(radioGridInvisible)
                            .addComponent(radioGridBW)
                            .addComponent(radioGridMinimal))))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioGridNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioGridInvisible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioGridBW)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioGridMinimal)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void changedGridThemeSelection() {
        if (groupGridTheme.isSelected(radioGridNormal.getModel())) {
            parent.knotIcons = parent.knotIconsGrid;
        } else if (groupGridTheme.isSelected(radioGridInvisible.getModel())) {
            parent.knotIcons = parent.knotIconsClean;
        } else if (groupGridTheme.isSelected(radioGridBW.getModel())) {
            parent.knotIcons = parent.knotIconsBWNoGrid;
        } else if (groupGridTheme.isSelected(radioGridMinimal.getModel())) {
            parent.knotIcons = parent.knotIconsMinimal;
        }
        parent.grid.knotIcons = parent.knotIcons;
        parent.SQUARE_WIDTH = parent.knotIcons[0].getIconWidth() - 1;
        parent.SQUARE_HEIGHT = parent.knotIcons[0].getIconHeight() - 1;
        parent.grid.refreshImages();        
    }
    
    private void radioGridNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioGridNormalActionPerformed
        changedGridThemeSelection();
    }//GEN-LAST:event_radioGridNormalActionPerformed

    private void radioGridInvisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioGridInvisibleActionPerformed
        changedGridThemeSelection();
    }//GEN-LAST:event_radioGridInvisibleActionPerformed

    private void radioGridBWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioGridBWActionPerformed
        changedGridThemeSelection();
    }//GEN-LAST:event_radioGridBWActionPerformed

    private void radioGridMinimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioGridMinimalActionPerformed
        changedGridThemeSelection();
    }//GEN-LAST:event_radioGridMinimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new OptionsForm(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup groupGridTheme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton radioGridBW;
    private javax.swing.JRadioButton radioGridInvisible;
    private javax.swing.JRadioButton radioGridMinimal;
    private javax.swing.JRadioButton radioGridNormal;
    // End of variables declaration//GEN-END:variables
}
