/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RegurgitationForm.java
 *
 * Created on Dec 7, 2011, 4:23:55 AM
 */
package knottheorist;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.Collection;
import javax.swing.JPanel;
import knottheorist.PreGrid.SnakeLink;

/**
 *
 * @author mewer12
 */
public class RegurgitationForm extends javax.swing.JFrame {

    public PreGrid grid = null;
    public JPanel panel = null;

    /** Creates new form RegurgitationForm */
    public RegurgitationForm() {
        initComponents();
        panel = new JPanel() {

            public static final int scale = 10;

            @Override
            public void paint(Graphics g1) {
                super.paint(g1);
                Graphics2D g = (Graphics2D) g1;
                g.setColor(Color.LIGHT_GRAY);
                g.fillRect(0, 0, 1280, 1024);
                if (grid != null) {
                    int minX = 0;
                    int maxX = 0;
                    int minY = 0;
                    int maxY = 0;
                    boolean oneFound = false;
                    //VoidSet<Coord, PreSquare> grid = RegurgitationForm.this.grid.grid;
                    Collection<PreSquare> squares = grid.grid.set.values();
                    for (PreSquare p : squares) {
                        if (!oneFound) {
                            minX = p.coord.getX();
                            maxX = p.coord.getX();
                            minY = p.coord.getY();
                            maxY = p.coord.getY();
                            oneFound = true;
                        } else {
                            if (p.coord.getX() < minX) {
                                minX = p.coord.getX();
                            } else if (p.coord.getX() > maxX) {
                                maxX = p.coord.getX();
                            }
                            if (p.coord.getY() < minY) {
                                minY = p.coord.getY();
                            } else if (p.coord.getY() > maxY) {
                                maxY = p.coord.getY();
                            }
                        }
                    }

                    for (PreSquare p : grid.grid.set.values()) {
                        if (p.empty) {
                            continue;
                        }
                        if (p.isCrossing) {
                            g.setColor(new Color(0, 0, p.crossing.hashCode() % 256));
                        } else {
                            g.setColor(new Color(p.fromCross.hashCode() % 256, p.toCross.hashCode() % 256, 0));
                        }
                        g.fillRect(scale * (p.coord.x - minX) + 1, scale * (p.coord.y - minY) + 1, scale, scale);
                    }

                    if (grid.snake != null) {
                        for (SnakeLink l : grid.snake) {
                            g.setColor(Color.red);
                            g.drawLine(scale * (l.x1 - minX) + 1, scale * (l.y1 - minY) + 1, scale * (l.x2 - minX) + 1, scale * (l.y2 - minY) + 1);
                        }
                    }
                }
            }
        };
        jSplitPane1.setLeftComponent(panel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        boxContinue = new javax.swing.JCheckBox();
        boxStep = new javax.swing.JCheckBox();
        btnRender = new javax.swing.JButton();
        btnAbort = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(knottheorist.KnotTheoristApp.class).getContext().getResourceMap(RegurgitationForm.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jSplitPane1.setDividerLocation(400);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        boxContinue.setText(resourceMap.getString("boxContinue.text")); // NOI18N
        boxContinue.setName("boxContinue"); // NOI18N

        boxStep.setText(resourceMap.getString("boxStep.text")); // NOI18N
        boxStep.setName("boxStep"); // NOI18N

        btnRender.setText(resourceMap.getString("btnRender.text")); // NOI18N
        btnRender.setName("btnRender"); // NOI18N

        btnAbort.setText(resourceMap.getString("btnAbort.text")); // NOI18N
        btnAbort.setName("btnAbort"); // NOI18N
        btnAbort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxContinue, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(boxStep, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRender, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAbort, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boxContinue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxStep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(btnRender)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setName("jPanel2"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );

        setBounds(50, 50, 554, 475);
    }// </editor-fold>//GEN-END:initComponents

private void btnAbortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbortActionPerformed
    if (grid != null) {
        grid.abort = true;
    }
}//GEN-LAST:event_btnAbortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegurgitationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegurgitationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegurgitationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegurgitationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RegurgitationForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox boxContinue;
    public javax.swing.JCheckBox boxStep;
    private javax.swing.JButton btnAbort;
    private javax.swing.JButton btnRender;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
